[data]
most_cited_csv = "C:/Users/GODLEWSKI/OneDrive - unistra.fr/EDITORIAL & REFEREEING/Revue FINANCE/ranking/PoP/PoPCites_.csv"
top_citing_csv = "C:/Users/GODLEWSKI/OneDrive - unistra.fr/EDITORIAL & REFEREEING/Revue FINANCE/Python files/Top3CitingPapersPerSource.csv"
unified_papers_csv = "C:/Users/GODLEWSKI/OneDrive - unistra.fr/EDITORIAL & REFEREEING/Revue FINANCE/Python files/UnifiedPapers.csv"
edges_csv = "C:/Users/GODLEWSKI/OneDrive - unistra.fr/EDITORIAL & REFEREEING/Revue FINANCE/Python files/Edges.csv"

[cloud]
fallback_data_dir = "data"
